apiVersion: v1
kind: Service
metadata:
  name: auth # Replace with your desired name
spec:
  selector:
    app: auth
  type: LoadBalancer # Adjust type based on your needs (e.g., NodePort)
  ports:
  - port: 80 # External port (can be different from container port)
    targetPort: 3000
